### PR TITLE
gateway: handle get bucket location, as us-east-1

### PR DESCRIPTION
**Pull request by windkit**
## Related to Issue
#799

### CODE REVIEW

**Comment by mocchira** [comment]
@windkit LGTM anyway did you check if #799 fixed (now using s3cmd 2.0 have no problem at all?) also this is another request that we should add the test case for s3cmd 2.0 into leofs_client_tests and add that into CI pipelines. Can you do that?

**Comment by windkit** [comment]
@mocchira Yes I have checked with s3cmd 2.0.0

```
~/s3cmd-2.0.0$ ./s3cmd get s3://test/testd/testf --debug --force
DEBUG: s3cmd version 2.0.0
DEBUG: ConfigParser: Reading file '/home/wilson/.s3cfg'
DEBUG: ConfigParser: access_key->05...3_chars...
DEBUG: ConfigParser: access_token->
DEBUG: ConfigParser: add_encoding_exts->
DEBUG: ConfigParser: add_headers->
DEBUG: ConfigParser: bucket_location->US
DEBUG: ConfigParser: ca_certs_file->
DEBUG: ConfigParser: cache_file->
DEBUG: ConfigParser: check_ssl_certificate->True
DEBUG: ConfigParser: check_ssl_hostname->True
DEBUG: ConfigParser: cloudfront_host->cloudfront.amazonaws.com
DEBUG: ConfigParser: default_mime_type->binary/octet-stream
DEBUG: ConfigParser: delay_updates->False
DEBUG: ConfigParser: delete_after->False
DEBUG: ConfigParser: delete_after_fetch->False
DEBUG: ConfigParser: delete_removed->False
DEBUG: ConfigParser: dry_run->False
DEBUG: ConfigParser: enable_multipart->True
DEBUG: ConfigParser: encoding->UTF-8
DEBUG: ConfigParser: encrypt->False
DEBUG: ConfigParser: expiry_date->
DEBUG: ConfigParser: expiry_days->
DEBUG: ConfigParser: expiry_prefix->
DEBUG: ConfigParser: follow_symlinks->False
DEBUG: ConfigParser: force->False
DEBUG: ConfigParser: get_continue->False
DEBUG: ConfigParser: gpg_command->/usr/bin/gpg
DEBUG: ConfigParser: gpg_decrypt->%(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_encrypt->%(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_passphrase->...-3_chars...
DEBUG: ConfigParser: guess_mime_type->True
DEBUG: ConfigParser: host_base->192.168.100.35:8080
DEBUG: ConfigParser: host_bucket->
DEBUG: ConfigParser: human_readable_sizes->False
DEBUG: ConfigParser: invalidate_default_index_on_cf->False
DEBUG: ConfigParser: invalidate_default_index_root_on_cf->True
DEBUG: ConfigParser: invalidate_on_cf->False
DEBUG: ConfigParser: kms_key->
DEBUG: ConfigParser: limitrate->0
DEBUG: ConfigParser: list_md5->False
DEBUG: ConfigParser: log_target_prefix->
DEBUG: ConfigParser: long_listing->False
DEBUG: ConfigParser: max_delete->-1
DEBUG: ConfigParser: mime_type->
DEBUG: ConfigParser: multipart_chunk_size_mb->15
DEBUG: ConfigParser: multipart_max_chunks->10000
DEBUG: ConfigParser: preserve_attrs->True
DEBUG: ConfigParser: progress_meter->True
DEBUG: ConfigParser: put_continue->False
DEBUG: ConfigParser: recursive->False
DEBUG: ConfigParser: recv_chunk->65536
DEBUG: ConfigParser: reduced_redundancy->False
DEBUG: ConfigParser: requester_pays->False
DEBUG: ConfigParser: restore_days->1
DEBUG: ConfigParser: secret_key->80...6_chars...5
DEBUG: ConfigParser: send_chunk->65536
DEBUG: ConfigParser: server_side_encryption->False
DEBUG: ConfigParser: simpledb_host->sdb.amazonaws.com
DEBUG: ConfigParser: skip_existing->False
DEBUG: ConfigParser: socket_timeout->300
DEBUG: ConfigParser: stats->False
DEBUG: ConfigParser: stop_on_error->False
DEBUG: ConfigParser: storage_class->
DEBUG: ConfigParser: urlencoding_mode->normal
DEBUG: ConfigParser: use_https->False
DEBUG: ConfigParser: use_mime_magic->True
DEBUG: ConfigParser: verbosity->WARNING
DEBUG: ConfigParser: website_endpoint->http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
DEBUG: ConfigParser: website_error->
DEBUG: ConfigParser: website_index->index.html
DEBUG: Updating Config.Config cache_file ->
DEBUG: Updating Config.Config follow_symlinks -> False
DEBUG: Updating Config.Config force -> True
DEBUG: Updating Config.Config verbosity -> 10
DEBUG: Unicodising 'get' using UTF-8
DEBUG: Unicodising 's3://test/testd/testf' using UTF-8
DEBUG: Command: get
DEBUG: DeUnicodising u'testd/testf' using UTF-8
DEBUG: Unicodising 'testf' using UTF-8
DEBUG: Applying --exclude/--include
DEBUG: CHECK: testf
DEBUG: PASS: u'testf'
INFO: Summary: 1 remote files to download
DEBUG: DeUnicodising u'./testf' using UTF-8
DEBUG: Unicodising './testf' using UTF-8
DEBUG: DeUnicodising u'./testf' using UTF-8
DEBUG: DeUnicodising u'./testf' using UTF-8
DEBUG: CreateRequest: resource[uri]=/testd/testf
DEBUG: ===== Recv_file inner request to determine the bucket region =====
DEBUG: CreateRequest: resource[uri]=/
DEBUG: Using signature v4
DEBUG: get_hostname(test): 192.168.100.35:8080
DEBUG: canonical_headers = host:192.168.100.35:8080
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20171025T064902Z

DEBUG: Canonical Request:
GET
/test/
location=
host:192.168.100.35:8080
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20171025T064902Z
host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
----------------------
DEBUG: signature-v4 headers: {'x-amz-content-sha256': u'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': u'AWS4-HMAC-SHA256 Credential=05236/20171025/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=
d1e14d0f1c0c8f3e31bf7dc4496b555f1e5b4a64cbdd5749d188e24bbcf847e5', 'x-amz-date': '20171025T064902Z'}
DEBUG: Processing request, please wait...
DEBUG: get_hostname(test): 192.168.100.35:8080
DEBUG: ConnMan.get(): creating new connection: http://192.168.100.35:8080
DEBUG: non-proxied HTTPConnection(192.168.100.35, 8080)
DEBUG: format_uri(): /test/?location
DEBUG: Sending request method_string='GET', uri=u'/test/?location', headers={'x-amz-content-sha256': u'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': u'AWS4-HMAC-SHA256 Credential=05236/20171025/us-east-1/s3/aws4_request,SignedHeaders=
host;x-amz-content-sha256;x-amz-date,Signature=d1e14d0f1c0c8f3e31bf7dc4496b555f1e5b4a64cbdd5749d188e24bbcf847e5', 'x-amz-date': '20171025T064902Z'}, body=(0 bytes)
DEBUG: ConnMan.put(): connection put back to pool (http://192.168.100.35:8080#1)
DEBUG: Response:
{'data': '<VersioningConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"/>',
 'headers': {'connection': 'keep-alive',
             'content-length': '74',
             'content-type': 'application/xml',
             'date': 'Wed, 25 Oct 2017 06:49:03 GMT',
             'server': 'LeoFS'},
 'reason': 'OK',
 'status': 200}
DEBUG: ===== END recv_file Inner request to determine the bucket region ('us-east-1') =====
DEBUG: Using signature v4
DEBUG: get_hostname(test): 192.168.100.35:8080
DEBUG: canonical_headers = host:192.168.100.35:8080
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20171025T064902Z

DEBUG: Canonical Request:
GET
/test/testd/testf

host:192.168.100.35:8080
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20171025T064902Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
----------------------
DEBUG: signature-v4 headers: {'x-amz-content-sha256': u'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': u'AWS4-HMAC-SHA256 Credential=05236/20171025/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=
8349587ef914770b7d20c6b78b2403fe4a0404b15729609d6cbbceaa35fcddad', 'x-amz-date': '20171025T064902Z'}
download: 's3://test/testd/testf' -> './testf'  [1 of 1]
DEBUG: get_hostname(test): 192.168.100.35:8080
DEBUG: ConnMan.get(): re-using connection: http://192.168.100.35:8080#1
DEBUG: format_uri(): /test/testd/testf
DEBUG: Response:
{'headers': {'connection': 'keep-alive',
             'content-length': '143786',
             'content-type': 'application/octet-stream',
             'date': 'Wed, 25 Oct 2017 06:49:03 GMT',
             'etag': '"881f1f9e800e033d59e2d63e6ab81642"',
             'last-modified': 'Wed, 25 Oct 2017 06:48:36 GMT',
             'server': 'LeoFS',
             'x-amz-meta-s3cmd-attrs': 'atime:1508914074/ctime:1502153146/gid:2001/gname:rit/md5:881f1f9e800e033d59e2d63e6ab81642/mode:33261/mtime:1502153146/uid:506/uname:wilson'},
 'reason': 'OK',
 's3cmd-attrs': {'atime': '1508914074',
                 'ctime': '1502153146',
                 'gid': '2001',
                 'gname': 'rit',
                 'md5': '881f1f9e800e033d59e2d63e6ab81642',
                 'mode': '33261',
                 'mtime': '1502153146',
                 'uid': '506',
                 'uname': 'wilson'},
 'status': 200}
  65536 of 143786    45% in    0s    10.18 MB/sDEBUG: ConnMan.put(): connection put back to pool (http://192.168.100.35:8080#2)
 143786 of 143786   100% in    0s    20.57 MB/s  done
DEBUG: ReceiveFile: Computed MD5 = 881f1f9e800e033d59e2d63e6ab81642
DEBUG: DeUnicodising u'./testf' using UTF-8
DEBUG: set mtime to 1508881716.0
```

**Comment by mocchira** [comment]
@windkit OK. I will merge once test cases for s3cmd 2.0 added to leofs_client_tests.

**Comment by windkit** [comment]
@mocchira as there is no direct way to trigger location get in `s3cmd` I will just add the test case on the CI

 - s3cmd-2.0.0
 - V4 Signature

**Comment by mocchira** [comment]
@windkit OK. let me know once the CI start to run the test for s3cmd-2.0.0.

**Comment by mocchira** [comment]
@windkit if https://github.com/leo-project/leofs_concourse/compare/2bd256d2c5...a377ef0c15 this works fine then I'll merge.

**Comment by windkit** [comment]
@mocchira object copy seems not working now. I am checking it

**Comment by windkit** [comment]
@mocchira In general, `s3cmd` does not work in the CI, it is because the GET Object ACL is broken when object is cached. I have created a PR https://github.com/leo-project/leofs/pull/921

Regarding to this PR, the test is passed with `s3cmd-2.0.1`

**Comment by mocchira** [comment]
@windkit LGTM.

**Comment by vstax** [comment]
Was trying to figure out why this fix didn't work for me, it turns out that it was never merged into "develop" branch?

**Comment by mocchira** [comment]
@vstax Oops. Thanks for pointing that out!
@windkit Please send PR to develop again.

**Comment by windkit** [comment]
oh sorry, I got it on master branch.
new PR here https://github.com/leo-project/leofs/pull/925

**Comment by mocchira** [comment]
@windkit Confirmed and merged thanks.
@vstax Please give it a try.

**Pull request merged**
