### PR TITLE
gateway: Fixed for Range Request with only start offset

### PR DESCRIPTION
**Pull request by windkit**

### CODE REVIEW

**Comment by mocchira** [comment]
@windkit LGTM. one thing for tests. range_to_binary should have the unit test with enough cases covering all specs described on RFC.

**Comment by yosukehara** [comment]
Link: #937

**Comment by mocchira** [comment]
@windkit LGTM. Did you try to play the video stored in LeoFS on some browsers? I will try on some and after confirming the original problem reported on ML being solved, I will merge the PR.

**Comment by mocchira** [comment]
Confirmed on Chrome 62.0.3202.89

**Comment by mocchira** [comment]
Confirmed on FireFox 57.0

**Comment by windkit** [comment]
Confirmed on Firefox 56.0.2 (64-bit)

**Pull request merged**
