### PR TITLE
storage: Fix leofs/issues/702 and leofs/issues/704

### LINKED ISSUE #702: Objects created when storage node was down don't arrive there after it's up
There is cluster (it says "1.3.3" but it's actually devel version from a few days ago):

```
 [System Confiuration]
-----------------------------------+----------
 Item                              | Value    
-----------------------------------+----------
 Basic/Consistency level
-----------------------------------+----------
                    system version | 1.3.3
                        cluster Id | leofs_1
                             DC Id | dc_1
                    Total replicas | 2
          number of successes of R | 2
          number of successes of W | 1
          number of successes of D | 1
 number of rack-awareness replicas | 0
                         ring size | 2^128
-----------------------------------+----------
 Multi DC replication settings
-----------------------------------+----------
        max number of joinable DCs | 2
           number of replicas a DC | 1
-----------------------------------+----------
 Manager RING hash
-----------------------------------+----------
                 current ring-hash | c1d863d0
                previous ring-hash | c1d863d0
-----------------------------------+----------

 [State of Node(s)]
-------+-----------------------------+--------------+----------------+----------------+----------------------------
 type  |            node             |    state     |  current ring  |   prev ring    |          updated at         
-------+-----------------------------+--------------+----------------+----------------+----------------------------
  S    | storage_0@192.168.3.53      | running      | c1d863d0       | c1d863d0       | 2017-04-12 20:37:49 +0300
  S    | storage_1@192.168.3.54      | running      | c1d863d0       | c1d863d0       | 2017-04-10 18:14:14 +0300
  S    | storage_2@192.168.3.55      | running      | c1d863d0       | c1d863d0       | 2017-04-10 18:14:16 +0300
  G    | gateway_0@192.168.3.52      | running      | c1d863d0       | c1d863d0       | 2017-04-11 19:51:38 +0300
-------+-----------------------------+--------------+----------------+----------------+----------------------------
```

Note R=2, W=1 settings; they are for clearer experiment, though nothing really changes with R=1.

Gateway is in S3 mode. I stop storage_0 and try to put a file which is supposed to go there

```
[root@leo-s0 ~]# /usr/local/leofs/current/leo_storage/bin/leo_storage stop
ok

[root@leo-m1 leofs]# /usr/local/leofs/current/leofs-adm -p 10011 whereis body/t
-------+-----------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------+----------------------------
 del?  |            node             |             ring address             |    size    |   checksum   |  has children  |  total chunks  |     clock      |             when
-------+-----------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------+----------------------------
       | storage_0@192.168.3.53      |                                      |            |              |                |                |                |
       | storage_1@192.168.3.54      |                                      |            |              |                |                |                |
```

Upload file with that name:

```
$ s3cmd put t s3://body/t
upload: 't' -> 's3://body/t'  [1 of 1]
 24164 of 24164   100% in    0s     2.79 MB/s  done
```

Check it:
```
[root@leo-m1 leofs]# /usr/local/leofs/current/leofs-adm -p 10011 whereis body/t
-------+-----------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------+----------------------------
 del?  |            node             |             ring address             |    size    |   checksum   |  has children  |  total chunks  |     clock      |             when
-------+-----------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------+----------------------------
       | storage_0@192.168.3.53      |                                      |            |              |                |                |                |
       | storage_1@192.168.3.54      | 279ec5e94b75559a7f03d707475aac09     |        24K |   ed57a247d7 | false          |              0 | 54cfbe4869229  | 2017-04-12 20:53:58 +0300
```

This is expected since storage_0 is not running. There are no errors on gateway or anywhere else.

queues for storage_1 are empty:
```
[root@leo-m0 leo_manager_0]# /usr/local/bin/leofs-adm mq-stats storage_1@192.168.3.54
              id                |    state    | number of msgs | batch of msgs  |    interval    |                 description
--------------------------------+-------------+----------------|----------------|----------------|---------------------------------------------
 leo_delete_dir_queue           |   idling    | 0              | 1600           | 500            | remove directories
 leo_comp_meta_with_dc_queue    |   idling    | 0              | 1600           | 500            | compare metadata w/remote-node
 leo_sync_obj_with_dc_queue     |   idling    | 0              | 1600           | 500            | sync objs w/remote-node
 leo_recovery_node_queue        |   idling    | 0              | 1600           | 500            | recovery objs of node
 leo_async_deletion_queue       |   idling    | 0              | 1600           | 500            | async deletion of objs
 leo_rebalance_queue            |   idling    | 0              | 1600           | 500            | rebalance objs
 leo_sync_by_vnode_id_queue     |   idling    | 0              | 1600           | 500            | sync objs by vnode-id
 leo_per_object_queue           |   idling    | 0              | 1600           | 500            | recover inconsistent objs
```

Launch storage_0:
```
[root@leo-s0 ~]# /usr/local/leofs/current/leo_storage/bin/leo_storage start

(wait a bit)

[root@leo-m0 leo_manager_0]# /usr/local/bin/leofs-adm status|grep storage_0
  S    | storage_0@192.168.3.53      | running      | c1d863d0       | c1d863d0       | 2017-04-12 20:58:25 +0300
```

Queues for both storage_1 and storage_0 are empty at this point.

Check if file has arrived to storage_0:
```
[root@leo-m1 leofs]# /usr/local/leofs/current/leofs-adm -p 10011 whereis body/t
-------+-----------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------+----------------------------
 del?  |            node             |             ring address             |    size    |   checksum   |  has children  |  total chunks  |     clock      |             when
-------+-----------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------+----------------------------
       | storage_0@192.168.3.53      |                                      |            |              |                |                |                |
       | storage_1@192.168.3.54      | 279ec5e94b75559a7f03d707475aac09     |        24K |   ed57a247d7 | false          |              0 | 54cfbe4869229  | 2017-04-12 20:53:58 +0300
```

The file will never arrive by itself.

Get operation:
```
$ s3cmd get s3://body/t
download: 's3://body/t' -> './t'  [1 of 1]
ERROR: S3 error: 500 (Internal Server Error)
```

Gateway log:
```
[W]	gateway_0@192.168.3.52	2017-04-12 21:14:39.246691 +0300	1492020879	leo_gateway_rpc_handler:handle_error/5298	[{node,'storage_0@192.168.3.53'},{mod,leo_storage_handler_object},{method,get},{cause,"Recover failure"}]
```

storage_0 log:
```
[W]	storage_0@192.168.3.53	2017-04-12 21:14:39.244455 +0300	1492020879	leo_storage_read_repairer:compare/4	165	[{node,'storage_0@192.168.3.53'},{addr_id,52664288857467231319818289008116149257},{key,<<"body/t">>},{clock,1492019638080041},{cause,not_found}]
[E]	storage_0@192.168.3.53	2017-04-12 21:14:39.247048 +0300	1492020879	leo_storage_handler_object:get/4	179	[{from,gateway},{method,get},{key,<<"body/t">>},{req_id,41524360},{etag,315482056269968508120622703193617812632},{cause,"Recover failure"}]
```

With these messages, object arrives to storage_0:
```
[root@leo-m1 leofs]# /usr/local/leofs/current/leofs-adm -p 10011 whereis body/t
-------+-----------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------+----------------------------
 del?  |            node             |             ring address             |    size    |   checksum   |  has children  |  total chunks  |     clock      |             when
-------+-----------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------+----------------------------
       | storage_0@192.168.3.53      | 279ec5e94b75559a7f03d707475aac09     |        24K |   ed57a247d7 | false          |              0 | 54cfbe4869229  | 2017-04-12 20:53:58 +0300
       | storage_1@192.168.3.54      | 279ec5e94b75559a7f03d707475aac09     |        24K |   ed57a247d7 | false          |              0 | 54cfbe4869229  | 2017-04-12 20:53:58 +0300
```

```
$ s3cmd get s3://body/t
download: 's3://body/t' -> './t'  [1 of 1]
 24164 of 24164   100% in    0s  1940.12 kB/s  done
```

Why it never arrived by itself? Shouldn't queue mechanism care of objects that need to be written while the node was down?

### PR DESCRIPTION
**Pull request by yosukehara**
I've fixed #702 and #704.

### CODE REVIEW

**Comment by mocchira** [comment]
WIP

**Comment by yosukehara** [comment]
I'm going to fix https://github.com/leo-project/leofs/issues/704#issuecomment-294062855

**Comment by yosukehara** [comment]
@mocchira Done https://github.com/leo-project/leofs/issues/704#issuecomment-294062855 and its related fix.

**Comment by mocchira** [comment]
@yosukehara LGTM.

Since a part of code implemented in the first commit got rollbacked on the second one,
Can I squash merge into one commit with "Fix leofs/issues/702 and leofs/issues/704" for the clarity?

**Comment by yosukehara** [comment]
@mocchira Done

**Pull request merged**
