### PR TITLE
Added V4 Operation to Basho Bench Driver

### PR DESCRIPTION
**Pull request by windkit**
### Brief Description
Added V4 Support to Basho Bench driver

### Related Pull Requests
 - https://github.com/leo-project/leo_gateway/pull/24
 - https://github.com/leo-project/leo_s3_libs/pull/2
 - https://github.com/leo-project/leo_commons/pull/3

### CODE REVIEW

**Comment by yosukehara** [comment]
@windkit Thank you for your contribution. We'll check your request.
@mocchira Do you think you could check this request? Then if there is no issues, you could merge it with ``1.4-branch``.

**Comment by mocchira** [comment]
@yosukehara @windkit Sorry. This place is obsolete.
Since the latest code has been currently manged at https://github.com/leo-project/basho_bench to make it easy for building and maintaining the own basho_bench,
Please PR to that repo.

I will remove the code placed here later.

**Comment by windkit** [comment]
Pull Request added
https://github.com/leo-project/basho_bench/pull/1

**Comment by windkit** [comment]
It seems confusing/misleading to leave the driver at `leofs/test/src`

**Comment by yosukehara** [comment]
I understood that. This solution is the benchmark files are managed at [under priv/test/ directory](https://github.com/leo-project/leofs/tree/develop/priv/test/), I think.

**Comment by windkit** [comment]
In particular, I refer to the basho bench driver, `basho_bench_driver_leofs.erl`. As suggested above, the code is actually moved to `leo-project/basho_bench` repo, leaving an obsolete version at `leo-project/leofs/test/src/` in `1.4` branch is a bit confusing

We will have to modify the benchmark section in the documentation for 1.4 too.

**Comment by yosukehara** [comment]
Thanks for your suggestion.
I'll move under ``leofs/test`` directory to [leo-prject/basho_bench](https://github.com/leo-project/basho_bench), then modify the documentation.

**Pull request closed without merging**
